#version: '3.8'


services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    restart: always
    ports:
      - "8000:8000"
    
    
    volumes:
            - ./jupyter_notebook:/jupyter_notebook

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.streamlit
    restart: always
    ports:
      - "8501:8501"
    